# infrastructure/images/db/Dockerfile
FROM postgres:13

# Set environment variables (you can also use an .env file)
ENV POSTGRES_USER=myuser
ENV POSTGRES_PASSWORD=mypassword
ENV POSTGRES_DB=mydb

# Expose the PostgreSQL port
EXPOSE 5432
