version: '3.9'
services:
  goteamgo-app:
    build:
      context: ..
      dockerfile: infrastructure/images/app/Dockerfile
    container_name: goteamgo-app
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
      - "19003:19003"
      - "19004:19004"
      - "19005:19005"
      - "19006:19006"
    volumes:
      - ../src/containers/goteamgo-app:/usr/src/app
      - node_modules:/usr/src/app/node_modules


  #   env_file:
  #     - images/web/.env
  goteamgo-server:
    build:
      context: ..
      dockerfile: infrastructure/images/server/Dockerfile
    container_name: goteamgo-server
    ports:
      - "5000:5000"
    # env_file:
    #   - images/server/.env
  goteamgo-db:
    build:
      context: ..
      dockerfile: infrastructure/images/db/Dockerfile
    container_name: goteamgo-db
    ports:
      - "5432:5432"
    volumes:
      - ../data/db/pgdata:/var/lib/postgresql/data
    # env_file:
    #   - images/db/.env

  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
    environment:
      - sonar.jdbc.url=jdbc:postgresql://goteamgo-db:5432/sonar
      - sonar.jdbc.username=sonar
      - sonar.jdbc.password=sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  node_modules:
  
